spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee_shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # 운영에서는 validate 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

        app:
          order-page-url: http://localhost:8081/order   # <- 팀 주문 URL로 수정해서 사용
          # 팀원이 같은 서버에서 /order 라우트를 쓰면 http://localhost:8080/order 로 적어도 된다.

